- hosts: localhost
  tasks:
#        - package:
#                name: docker
#                state: present
        
        - docker_container:
                name: sherlock_homes
                image: centos
                tty: True
                interactive: True
                state: started
